### ISSUE TITLE
Prime Sieve - Sporadic Error

### ISSUE THREAD

**Issue by LingUaan** [kimwalisch/primesieve#25] opened 2017-01-10 07:18 UTC
The error happens once for about every 5.000 to 10.000 calls to the prime sieve program. For every call I let it sieve a range of 10^11 numbers. If the error happens it counts 1 ... 10 primes too much, hardly ever too less. Very rarely the miscount is larger than 10. If I run the program again on an erroneous range the count is going to be correct, that is the error is sporadic, it cannot be duplicated.
My test frame compares the results with the prime sieve tables of Tomás Oliveira e Silva.
The error probability and the error magnitude is always pretty much the same, regardless of:
-	Compiler (Intel, Borland, Clang, G++ (Cygwin)
-	Compile optimization -o1 or -o2 or -o3
-	Linked to test frame, as DLL or EXE or primesieve.exe itself
-	OpenMP, or ‚manual‘ thread synchronization
-	Number of Threads (4, 6, 8, 10, 12)
-	Processor (Q6600, i7 X980 Black Edition)
-	Overclocked or regular processor speed
-	OS (Vista, W7)
-	Version 5.4 or 5.7 or any other
-	Time between launches 0,1s or 1s or more
-	What range to be sieved
I’ve sieved so far about 10^17 numbers and still have no clue of what is causing the errors nor why. Of course there are the usual suspects like: Rounding error, Timing problem etc.

**Comment by kimwalisch** [comment] 2017-01-10 08:22
Can your PC pass primesieve's test suite successfully (run it at least 3 times):

$ ./primesieve --test

Can you please provide a script (or the program) which produces the bug on your PC? I will then try to reproduce the bug later today.

**Comment by LingUaan** [comment] 2017-01-10 10:43
Here my reply.
Best Regards.

I run the primesieve.exe V5.7.2 as provided from the prime sieve homepage.
I  launch it from my test frame like this:

      iStartValue = ThreadData->ui64StartValue;
      iStopValue  = ThreadData->ui64StartValue + ThreadData->iInterval;

      float fZeit;

      String uzStart = iStartValue;
      String uzStop = iStopValue;
      String lpParameters = uzStart + " " +  uzStop;
      lpParameters += " -t10";
      lpParameters += " -q --time";
      lpParameters += " -s64";

      SHELLEXECUTEINFO ShExecInfo = {0};                  // run primesieve
        ShExecInfo.cbSize = sizeof(SHELLEXECUTEINFO);
        ShExecInfo.fMask = SEE_MASK_NOCLOSEPROCESS;
        ShExecInfo.hwnd = NULL;
        ShExecInfo.lpVerb = NULL;
        ShExecInfo.lpFile = L"d:/Borland/Sieb11/Sieb.bat";
        ShExecInfo.lpParameters = lpParameters.w_str();
        ShExecInfo.lpDirectory = NULL;
        ShExecInfo.nShow = SW_HIDE; // SW_SHOW
        ShExecInfo.hInstApp = NULL;
      ShellExecuteEx(&ShExecInfo);
      WaitForSingleObject(ShExecInfo.hProcess,INFINITE);  // wait for the result


        std::string S1, S2, S3, S4, S5, S6;

        ifstream myfile;
        myfile.open ("Save.txt", ios::out );
        myfile >> S1 >> S2 >> fZeit >> S4 >> S5 >> iCount1;
        myfile.close();

      ThreadData->iZeitStop = fZeit * 1000;
      Synchronize( &CollectResults);


[primetest4.txt](https://github.com/kimwalisch/primesieve/files/695847/primetest4.txt)
[primetest2.txt](https://github.com/kimwalisch/primesieve/files/695848/primetest2.txt)
[primetest5.txt](https://github.com/kimwalisch/primesieve/files/695850/primetest5.txt)
[primetest1.txt](https://github.com/kimwalisch/primesieve/files/695849/primetest1.txt)
[primetest3.txt](https://github.com/kimwalisch/primesieve/files/695851/primetest3.txt)

[Sieb.bat.txt](https://github.com/kimwalisch/primesieve/files/695855/Sieb.bat.txt)
[primesieve.exe.txt](https://github.com/kimwalisch/primesieve/files/695854/primesieve.exe.txt)

**Comment by kimwalisch** [comment] 2017-01-10 11:12
Thanks for your feedback!

Can you provide the start an stop numbers for a range where you witnessed an error? I will then simply run that range e.g. 10.000 times to reproduce the bug.

**Comment by LingUaan** [comment] 2017-01-10 13:32
Sure, for example:
76.343.500.000.000.000 … 76.343.600.000.000.000
77.565.400.000.000.000 … 77.565.500.000.000.000
99.033.600.000.000.000 … 99.033.700.000.000.000

**Comment by kimwalisch** [comment] 2017-01-10 14:38
One more question:

This bug reminds me of a similar bug Andrey Kulsha reported to me in 2014. He was sieving in intervals of 10^9 up to 10^17. About every two weeks he encountered a mis-count (by double checking). His system was overclocked, I asked him to run the prime95 stress test which showed that his PC was unstable.

Could you please also run the prime95 stress test on your system? I know you encountered the bug on a non-overclocked PC but I think there is still a high probability that your PC is unstable as no other user has reported that bug over the last 1-2 years.

Thanks!

Thanks.

**Comment by LingUaan** [comment] 2017-01-10 16:36
![prime95torturetestresult](https://cloud.githubusercontent.com/assets/25026601/21814939/4a82a4fa-d75b-11e6-861d-a1e41a2dac31.jpg)

**Comment by kimwalisch** [comment] 2017-01-10 16:57
Thanks, this means that there is a bug somewhere in primesieve.

I have started running './primesieve 76343500000000000 76343600000000000 -s64 -q' in a loop on a fast Linux server (18 CPU cores, 36 threads).

You mentioned that you have seen the bug using different compilers. Have you also seen the bug with OpenMP (multi-threading) disabled? Or did you always compile primesieve with OpenMP?

**Comment by kimwalisch** [comment] 2017-01-10 22:09
I have run './primesieve 76343500000000000 76343600000000000 -s64 -q' a total of 16.000 times and each iteration produced the same result. This was on Linux servers with Intel Xeon CPUs with ECC memory correction and the primesieve-5.7.2 Linux binary downloaded from http://primesieve.org/downloads.

So I have not been able to reproduce the bug so far. I will test on Windows over the next days...

**Comment by LingUaan** [comment] 2017-01-11 04:45
I saw it with OpenMP disabled too. Because the Borland Compiler doesn't support OpenMP. And that is the setup I worked most of the time with. 
Only lately I tried it with G++ (CygWin) and primesieve.exe but with the same result.

**Comment by kimwalisch** [comment] 2017-01-11 21:59
I have now also tested the primesieve-5.7.2 Windows binary from http://primesieve.org/downloads. I have run 'primesieve.exe 76343500000000000 76343600000000000 -s64 -q -t10' a total of 8000 times and each iteration reported the same result. (The tests were run on fast Linux servers with ECC memory correction and Wine which is a free implementation of Windows on Unix)

I have further tested primesieve extensively using valgrind (which detects memory leaks and data races at run-time) and using GCC sanitizers which can also detect a wide range of common bugs at runtime and no issues have been found.

**Summary:**

* As you have seen the bug using multiple compilers the bug is not a compiler bug.
* As you have also seen the bug with OpenMP disabled the bug is not a multi-threading bug.
* I have not been able to reproduce the bug using the primesieve Linux and Windows binaries (all tests have been run on Linux servers with ECC memory correction).
* Neither valgrind nor GCC sanitizers have detected any issues in primesieve.
* No other user has reported a similar primesieve bug over the past years.

**Conclusion:**

I don't think the bug you experience regularly every 5000 to 10000 calls is a bug in primesieve. My guess is your bug is either a Windows bug or the bug is caused by a buggy RAM DIMM module of yours. I will hence stop investigating this bug for the time being.

**Comment by kimwalisch** [comment] 2017-01-12 21:27
I have now run another 6000 tests of the primesieve-5.7.2 Windows binary using the script below:

```bash
#!/bin/bash
start=76343500000000000

for i in {1..6000}
do
	count1=$(wine ./primesieve.exe $start -d1e11 -q 2> /dev/null)
	count2=$(wine ./primesieve.exe $start -d1e11 -q -s64 -t10 2> /dev/null)
	start=$(($start + 10**11))

	if [ "$count1" == "$count2" ]
	then
		echo $i
	else
		echo "$count1 != $count2"
		exit 1
	fi
done
```

All test results matched i.e. I was unable to reproduce the bug you have reported.
Hence I close this issue.

**Closed by kimwalisch** 2017-01-12 21:27 UTC
